import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import confetti from 'canvas-confetti';
import { ProjectIdea } from '../types';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function triggerCelebration() {
  confetti({
    particleCount: 80,
    spread: 70,
    origin: { y: 0.6 },
    colors: ['#6366f1', '#3b82f6', '#10b981', '#f59e0b', '#ec4899']
  });
}

export function getDifficultyColor(level: string): { bg: string; text: string; border: string } {
  switch (level?.toLowerCase()) {
    case 'beginner':
      return { bg: 'bg-emerald-500/10', text: 'text-emerald-400', border: 'border-emerald-500/30' };
    case 'intermediate':
      return { bg: 'bg-amber-500/10', text: 'text-amber-400', border: 'border-amber-500/30' };
    case 'advanced':
    default:
      return { bg: 'bg-indigo-500/10', text: 'text-indigo-400', border: 'border-indigo-500/30' };
  }
}

export function getScoreColor(score: number): string {
  if (score >= 85) return 'text-emerald-400';
  if (score >= 70) return 'text-cyan-400';
  if (score >= 50) return 'text-amber-400';
  return 'text-rose-400';
}

export function exportProjectAsMarkdown(project: ProjectIdea) {
  const md = `# ${project.title}
**Domain**: ${project.domain} | **Difficulty**: ${project.difficultyLevel} (${project.difficultyScore}/10) | **Innovation**: ${project.innovationScore}/10
**Estimated Duration**: ${project.estimatedTime} | **Team Format**: ${project.teamType}
**Project Type**: ${project.projectType}
**Readiness Score**: ${project.readinessScore || 'N/A'}/100

---

## 1. Problem Statement
${project.problemStatement}

## 2. Description
${project.description}

## 3. Core Objectives
${project.objectives.map(o => `- ${o}`).join('\n')}

## 4. Target Users
${project.targetUsers.map(u => `- ${u}`).join('\n')}

## 5. Technology Stack Requirements
- **Required Technologies**: ${project.technologiesRequired.join(', ')}
- **Software Dependencies**: ${project.softwareRequirements.join(', ')}
- **Database Architecture**: ${project.databaseRequirements.join(', ')}
${project.hardwareRequirements?.length ? `- **Hardware Requirements**: ${project.hardwareRequirements.join(', ')}` : ''}
${project.aiMlAlgorithms?.length ? `- **AI/ML Algorithms**: ${project.aiMlAlgorithms.join(', ')}` : ''}

## 6. Modular Development Breakdown
${project.developmentModules.map(m => `### ${m.name}\n${m.description}\n*Deliverables*: ${m.deliverables.join(', ')}`).join('\n\n')}

## 7. System Architecture Explanation
${project.systemArchitectureExplanation}

## 8. Suggested REST APIs
${project.apiSuggestions.map(a => `- \`${a.method} ${a.endpoint}\`: ${a.description}`).join('\n')}

## 9. Scalability Strategy
${project.scalabilitySuggestions.map(s => `- ${s}`).join('\n')}

## 10. Future Enhancements
${project.futureEnhancements.map(e => `- ${e}`).join('\n')}

---
*Generated by AI Innovation Lab* - ${new Date().toLocaleDateString()}
`;

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_spec.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportProjectAsJSON(project: ProjectIdea) {
  const jsonStr = JSON.stringify(project, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_data.json`;
  a.click();
  URL.revokeObjectURL(url);
}
