import React, { useState } from 'react';
import {
  GitFork,
  CheckCircle2,
  Plus,
  Clock,
  Calendar,
  RefreshCw,
  FileDown,
  Check,
  ChevronDown,
  ChevronUp,
  Tag,
  Terminal,
  Activity
} from 'lucide-react';
import { ProjectIdea, RoadmapData, RoadmapPhase, RoadmapTask } from '../types';
import { api } from '../lib/api';
import { triggerCelebration } from '../lib/utils';

interface RoadmapViewProps {
  activeProject?: ProjectIdea | null;
  savedProjects: ProjectIdea[];
  onSaveRoadmap?: (projectId: string, roadmap: RoadmapData) => void;
}

export const RoadmapView: React.FC<RoadmapViewProps> = ({
  activeProject,
  savedProjects,
  onSaveRoadmap
}) => {
  const [selectedProject, setSelectedProject] = useState<ProjectIdea | null>(
    activeProject || savedProjects[0] || null
  );
  const [roadmap, setRoadmap] = useState<RoadmapData | null>(
    activeProject?.roadmap || (savedProjects[0]?.roadmap ?? null)
  );
  const [loading, setLoading] = useState(false);
  const [expandedPhaseId, setExpandedPhaseId] = useState<number | null>(1);
  const [newTaskTitle, setNewTaskTitle] = useState<string>('');
  const [targetPhaseId, setTargetPhaseId] = useState<number>(1);

  const handleGenerateRoadmap = async (proj: ProjectIdea) => {
    setLoading(true);
    try {
      const data = await api.generateRoadmap({
        title: proj.title,
        domain: proj.domain,
        description: proj.description,
        duration: proj.estimatedTime,
        projectId: proj.id
      });
      setRoadmap(data);
      if (onSaveRoadmap) {
        onSaveRoadmap(proj.id, data);
      }
    } catch (err) {
      console.error('Failed to generate roadmap:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectProjectChange = (projId: string) => {
    const proj = savedProjects.find(p => p.id === projId);
    if (proj) {
      setSelectedProject(proj);
      if (proj.roadmap) {
        setRoadmap(proj.roadmap);
      } else {
        handleGenerateRoadmap(proj);
      }
    }
  };

  const handleToggleTask = (phaseNumber: number, taskId: string) => {
    if (!roadmap) return;

    const updatedPhases = roadmap.phases.map(phase => {
      if (phase.phaseNumber === phaseNumber) {
        const updatedTasks = phase.tasks.map(t => {
          if (t.id === taskId) {
            return { ...t, completed: !t.completed };
          }
          return t;
        });

        return {
          ...phase,
          tasks: updatedTasks
        };
      }
      return phase;
    });

    const totalTasks = updatedPhases.flatMap(p => p.tasks).length;
    const completedTasks = updatedPhases.flatMap(p => p.tasks).filter(t => t.completed).length;
    const completionPercentage = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

    const updatedRoadmap: RoadmapData = {
      ...roadmap,
      phases: updatedPhases,
      completionPercentage
    };

    setRoadmap(updatedRoadmap);
    if (completionPercentage === 100) {
      triggerCelebration();
    }
  };

  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle.trim() || !roadmap) return;

    const newTask: RoadmapTask = {
      id: `task-custom-${Date.now()}`,
      title: newTaskTitle.trim(),
      description: 'Custom added task item',
      durationDays: 2,
      priority: 'Medium',
      dependencies: [],
      completed: false
    };

    const updatedPhases = roadmap.phases.map(p => {
      if (p.phaseNumber === targetPhaseId) {
        return {
          ...p,
          tasks: [...p.tasks, newTask]
        };
      }
      return p;
    });

    const totalTasks = updatedPhases.flatMap(p => p.tasks).length;
    const completedTasks = updatedPhases.flatMap(p => p.tasks).filter(t => t.completed).length;
    const completionPercentage = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

    setRoadmap({
      ...roadmap,
      phases: updatedPhases,
      completionPercentage
    });

    setNewTaskTitle('');
  };

  const exportRoadmapMarkdown = () => {
    if (!roadmap) return;
    const md = `# Development Roadmap: ${selectedProject?.title || 'Project'}
**Estimated Total Duration**: ~${roadmap.totalDurationWeeks} Weeks
**Current Progress**: ${roadmap.completionPercentage}% Completed

---

${roadmap.phases.map(p => `## Phase ${p.phaseNumber}: ${p.phaseName} (${p.durationWeeks})
*Goals: ${p.goals}*

### Tasks:
${p.tasks.map(t => `- [${t.completed ? 'x' : ' '}] ${t.title} (~${t.durationDays}d) - Priority: ${t.priority}`).join('\n')}
`).join('\n---\n\n')}

*Generated by AI Innovation Lab* - ${new Date().toLocaleDateString()}
`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(selectedProject?.title || 'project').toLowerCase().replace(/[^a-z0-9]/g, '_')}_roadmap.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#2D3748] pb-6">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono font-semibold mb-2">
            <GitFork className="w-3.5 h-3.5" />
            <span>AI 8-PHASE ROADMAP & SPRINT TRACKER</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            Comprehensive 8-Phase Development Roadmap
          </h1>
          <p className="text-xs text-slate-400 mt-1 max-w-3xl">
            Track implementation from requirements analysis and API contracts to containerized CI/CD deployment.
          </p>
        </div>

        {/* Project Selector & Actions */}
        <div className="flex items-center gap-3 font-mono">
          <select
            id="roadmap-project-select"
            value={selectedProject?.id || ''}
            onChange={e => handleSelectProjectChange(e.target.value)}
            className="bg-[#151921] border border-[#2D3748] text-xs text-slate-200 rounded px-3 py-2 focus:outline-none focus:border-sky-500 max-w-[220px] truncate"
          >
            {savedProjects.map(p => (
              <option key={p.id} value={p.id}>
                {p.title}
              </option>
            ))}
          </select>

          {selectedProject && (
            <button
              id="regenerate-roadmap-btn"
              onClick={() => handleGenerateRoadmap(selectedProject)}
              disabled={loading}
              className="flex items-center gap-1.5 px-3 py-2 rounded bg-sky-500 hover:bg-sky-400 text-slate-950 text-xs font-bold transition-all disabled:opacity-50 uppercase tracking-wider"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
              <span>{loading ? 'Building...' : 'Regenerate'}</span>
            </button>
          )}

          {roadmap && (
            <button
              onClick={exportRoadmapMarkdown}
              className="flex items-center gap-1 px-3 py-2 rounded bg-[#151921] hover:bg-[#1E2633] text-slate-300 border border-[#2D3748] text-xs font-mono"
            >
              <FileDown className="w-3.5 h-3.5" />
              <span>.MD</span>
            </button>
          )}
        </div>
      </div>

      {loading ? (
        <div className="glass rounded-xl p-12 flex flex-col items-center justify-center space-y-4 shadow-2xl font-mono">
          <div className="w-12 h-12 rounded bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <GitFork className="w-6 h-6 animate-spin" />
          </div>
          <div className="text-center space-y-1">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider">Synthesizing 8 Development Phases</h3>
            <p className="text-xs text-emerald-300 font-mono">Estimating work hours, task milestones, and testing procedures...</p>
          </div>
        </div>
      ) : roadmap ? (
        <div className="space-y-6">
          {/* Progress Overview Hero Card */}
          <div className="glass rounded-xl p-6 shadow-2xl space-y-4 font-mono">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <span className="text-[10px] font-bold uppercase text-emerald-400 tracking-wider">ACTIVE ROADMAP SPEC</span>
                <h2 className="text-lg font-bold text-white tracking-tight">{selectedProject?.title || 'Project Plan'}</h2>
                <p className="text-xs text-slate-400 mt-0.5 flex items-center gap-2 font-sans">
                  <Calendar className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Timeline Horizon: <strong className="text-slate-200">~{roadmap.totalDurationWeeks} Weeks</strong></span>
                </p>
              </div>

              {/* Progress Circle & Status */}
              <div className="flex items-center gap-4">
                <div className="text-right">
                  <div className="text-2xl font-extrabold text-emerald-400">{roadmap.completionPercentage}%</div>
                  <div className="text-[9px] text-slate-400 uppercase font-semibold">COMPLETED</div>
                </div>
                <div className="w-12 h-12 rounded-full bg-[#0B0E14] border-2 border-emerald-500/50 flex items-center justify-center shadow-inner">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                </div>
              </div>
            </div>

            {/* Progress Bar */}
            <div className="w-full bg-[#0B0E14] h-2 rounded overflow-hidden border border-[#2D3748]">
              <div
                className="h-full bg-gradient-to-r from-emerald-400 to-sky-400 transition-all duration-500"
                style={{ width: `${roadmap.completionPercentage}%` }}
              />
            </div>
          </div>

          {/* Quick Task Adder */}
          <form onSubmit={handleAddTask} className="glass p-3 rounded-lg flex flex-col sm:flex-row items-center gap-3 font-mono">
            <input
              type="text"
              value={newTaskTitle}
              onChange={e => setNewTaskTitle(e.target.value)}
              placeholder="Add custom task (e.g. 'Setup Sentry error tracking')..."
              className="flex-1 bg-[#0B0E14] border border-[#2D3748] rounded px-3 py-1.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-sky-500"
            />
            <div className="flex items-center gap-2 w-full sm:w-auto">
              <select
                value={targetPhaseId}
                onChange={e => setTargetPhaseId(Number(e.target.value))}
                className="bg-[#0B0E14] border border-[#2D3748] rounded px-3 py-1.5 text-xs text-white focus:outline-none focus:border-sky-500"
              >
                {roadmap.phases.map(p => (
                  <option key={p.phaseNumber} value={p.phaseNumber} className="bg-[#151921]">
                    Phase {p.phaseNumber}
                  </option>
                ))}
              </select>
              <button
                type="submit"
                className="px-3.5 py-1.5 rounded bg-sky-500 hover:bg-sky-400 text-slate-950 text-xs font-bold whitespace-nowrap uppercase tracking-wider"
              >
                + Add Task
              </button>
            </div>
          </form>

          {/* 8 Phases List */}
          <div className="space-y-3">
            {roadmap.phases.map((phase) => {
              const isExpanded = expandedPhaseId === phase.phaseNumber;
              const completedCount = phase.tasks.filter(t => t.completed).length;
              const isAllDone = completedCount === phase.tasks.length && phase.tasks.length > 0;

              return (
                <div
                  key={phase.phaseNumber}
                  id={`roadmap-phase-${phase.phaseNumber}`}
                  className={`glass rounded-xl overflow-hidden transition-all duration-150 shadow-md ${
                    isExpanded ? 'border-sky-500/50 shadow-[0_0_15px_rgba(56,189,248,0.1)]' : 'hover:border-slate-600'
                  }`}
                >
                  {/* Phase Header */}
                  <div
                    onClick={() => setExpandedPhaseId(isExpanded ? null : phase.phaseNumber)}
                    className="p-4 sm:p-5 cursor-pointer flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 select-none hover:bg-[#1A202C]/50 font-mono"
                  >
                    <div className="flex items-center gap-3">
                      <div className={`w-8 h-8 rounded flex items-center justify-center font-bold text-xs ${
                        isAllDone
                          ? 'bg-emerald-500 text-slate-950 font-extrabold'
                          : 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'
                      }`}>
                        {isAllDone ? <Check className="w-4 h-4 text-slate-950" /> : `P${phase.phaseNumber}`}
                      </div>

                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-[9px] font-bold uppercase text-sky-400">
                            Phase {phase.phaseNumber}
                          </span>
                          <span className="text-xs text-slate-400 font-sans">• {phase.durationWeeks}</span>
                        </div>
                        <h3 className="text-sm font-bold text-white">{phase.phaseName}</h3>
                      </div>
                    </div>

                    <div className="flex items-center gap-4 self-end sm:self-center">
                      <div className="text-right">
                        <span className="text-xs font-semibold text-slate-300">
                          {completedCount} / {phase.tasks.length} tasks
                        </span>
                      </div>

                      <button
                        type="button"
                        className="p-1 rounded bg-[#0B0E14] text-slate-300 border border-[#2D3748]"
                      >
                        {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                      </button>
                    </div>
                  </div>

                  {/* Expanded Phase Tasks & Milestones */}
                  {isExpanded && (
                    <div className="border-t border-[#2D3748] bg-[#0B0E14]/80 p-5 space-y-5 animate-fadeIn">
                      <p className="text-xs text-slate-300 leading-relaxed bg-[#151921] p-3 rounded border border-[#2D3748] font-sans">
                        <strong className="text-emerald-400 block mb-0.5 font-mono text-[10px] uppercase">Phase Objective:</strong> {phase.goals}
                      </p>

                      {/* Tasks Checklist */}
                      <div className="space-y-2.5 font-mono">
                        <h4 className="text-[11px] font-bold text-slate-200 uppercase tracking-wider">
                          Tasks & Action Items
                        </h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                          {phase.tasks.map(task => (
                            <div
                              key={task.id}
                              id={`task-item-${task.id}`}
                              onClick={() => handleToggleTask(phase.phaseNumber, task.id)}
                              className={`p-3 rounded border cursor-pointer flex items-start justify-between gap-3 transition-all ${
                                task.completed
                                  ? 'bg-emerald-950/20 border-emerald-500/40 text-slate-400 line-through'
                                  : 'bg-[#151921] border-[#2D3748] hover:border-slate-600 text-slate-200'
                              }`}
                            >
                              <div className="flex items-start gap-2.5">
                                <div className={`w-4 h-4 rounded flex items-center justify-center mt-0.5 ${
                                  task.completed ? 'bg-emerald-500 text-slate-950 font-bold' : 'border border-[#2D3748] bg-[#0B0E14]'
                                }`}>
                                  {task.completed && <Check className="w-3 h-3" />}
                                </div>
                                <div className="space-y-0.5">
                                  <span className="text-xs font-medium block">{task.title}</span>
                                  {task.description && (
                                    <p className="text-[10px] text-slate-400 no-underline font-sans">{task.description}</p>
                                  )}
                                </div>
                              </div>
                              <div className="flex flex-col items-end gap-1 flex-shrink-0">
                                <span className="text-[9px] text-slate-500 flex items-center gap-1">
                                  <Clock className="w-3 h-3" />
                                  ~{task.durationDays}d
                                </span>
                                <span className={`text-[8px] px-1.5 py-0.2 rounded font-bold uppercase ${
                                  task.priority === 'High' ? 'bg-rose-500/20 text-rose-300' : 'bg-[#0B0E14] text-slate-400'
                                }`}>
                                  {task.priority}
                                </span>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="glass rounded-xl p-12 text-center space-y-4 font-mono">
          <GitFork className="w-12 h-12 text-slate-600 mx-auto" />
          <h3 className="text-sm font-bold text-white uppercase tracking-wider">No Roadmap Generated Yet</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto font-sans">
            Select a project from the top dropdown or create a new project to produce an 8-phase task breakdown.
          </p>
        </div>
      )}
    </div>
  );
};
